##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (3)                        #
#                                                                                #
##################################################################################

package:
  name: python-statiskit_stl
  version: "3.3.1"

source:
  path: ../..

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]
        
about:
  home: statiskit.readthedocs.org
  license: CeCILL

requirements:
  build:
    - libdev
    - python-dev
    - libboost
    - libstatiskit_stl
    - python
  run:
    - librun
    - libstatiskit_stl
    - libboost
    - python

test:                                                           
  # source_files:                                 [not win]
  #   - test                                      [not win]
  # requires:                                     [not win]
  #   - libdev                                    [not win]
  #   - python-dev                                [not win]
  #   - python-dbg                                [not win]
  commands:                                       
   - python -c "import statiskit.stl.__stl" 
