package:
  name: python-statiskit_stl
  version: "3.3.1"

source:
  path: ../..

build:
  number: 0

about:
  home: statiskit.readthedocs.org
  license: CeCILL

requirements:
  build:
    - libdev
    - python-dev
    - libboost
    - libstatiskit_stl
    - python
  run:
    - librun
    - libstatiskit_stl
    - libboost
    - python

test:                                                           
  source_files:                                
    - test/test_*.py
  requires:
    - python-dbg
  commands:                                       
   - nosetests test -x -s -v
