package:
  name: python-statiskit_stl
  version: "3.3.1"

source:
  path: ../../..

build:
  number: 0

about:
  home: http://statiskit-stl.readthedocs.org
  license: CeCILL

requirements:
  build:
    - libdev
    - python-dev
    - libboost
    - libstatiskit_stl
    - python
  run:
    - librun
    - libstatiskit_stl
    - libboost
    - python

test:                                               
  requires:
    - python-dev
  imports:
    - statiskit.stl
  source_files:                                
    - test/test_*.py
  commands:                                       
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]
