package:
  name: libstatiskit_stl
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

about:
  home: http://statiskit-stl.readthedocs.org
  license: Apache License 2.0
  summary: Minimal Interpreted Interfaces for Containers of the STL C++ Template Library

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtoolchain
  host:
    - libstatiskit_stl-dev