package:
  name: libstatiskit_stl-dev
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  detect_binary_files_with_prefix: False
  
about:
  home: http://statiskit-stl.readthedocs.org
  license: Apache License 2.0
  summary: Minimal Interpreted Interfaces for Containers of the STL C++ Template Library

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtoolchain
    - libtoolchain-dev
    - autowig-toolchain             # [linux]
  host:
    - python